# Generated by Django 2.0.6 on 2020-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBlockSetting',
            fields=[
                ('block_id', models.IntegerField(primary_key=True, serialize=False)),
                ('block_size', models.IntegerField(blank=True, null=True)),
                ('last_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_block_setting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(blank=True, max_length=1, null=True)),
                ('fille_name', models.CharField(blank=True, max_length=50, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('last_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.FloatField(blank=True, null=True)),
                ('parent_file_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TGroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('friend_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_groom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='THistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('see_time', models.DateTimeField(blank=True, null=True)),
                ('see_cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TMessage',
            fields=[
                ('create_time', models.DateTimeField(auto_created=True, blank=True)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('link_url', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(0, '审核中'), (1, '已通过'), (2, '未通过')], default=0)),
            ],
            options={
                'db_table': 't_message',
                'ordering': ['-create_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSysRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 't_sys_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TSysUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('auth_string', models.CharField(max_length=32)),
                ('nick_name', models.CharField(blank=True, max_length=20, null=True)),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 't_sys_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_string', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('head', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': False,
            },
        ),
    ]
