# Generated by Django 2.0.6 on 2020-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='投诉id')),
                ('text', models.TextField(verbose_name='投诉内容')),
                ('reply_peoplr', models.CharField(max_length=20, null=True, verbose_name='回复人')),
                ('reply_text', models.TextField(null=True, verbose_name='回复内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '投诉管理',
                'verbose_name_plural': '投诉管理',
                'db_table': 'complaint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('evaluate_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='评价id')),
                ('text', models.TextField(verbose_name='评价内容')),
                ('reply_people', models.CharField(max_length=20, null=True, verbose_name='回复人')),
                ('reply_text', models.TextField(null=True, verbose_name='回复内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '评价管理',
                'verbose_name_plural': '评价管理',
                'db_table': 'evaluate',
                'managed': False,
            },
        ),
    ]
