# Generated by Django 2.0.6 on 2020-02-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aftsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='complaint',
        ),
        migrations.AlterModelTable(
            name='evaluate',
            table='evaluate',
        ),
    ]
