# Generated by Django 2.0.6 on 2020-02-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aftsale', '0002_auto_20200219_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'managed': False, 'verbose_name': '投诉管理', 'verbose_name_plural': '投诉管理'},
        ),
        migrations.AlterModelOptions(
            name='evaluate',
            options={'managed': False, 'verbose_name': '评价管理', 'verbose_name_plural': '评价管理'},
        ),
    ]
