# Generated by Django 2.0.6 on 2020-02-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=1)),
                ('status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '已取消')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.TicketInfo')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(1, '管理员'), (2, '用户')], default=2)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('user_number', models.CharField(max_length=18, null=True)),
                ('address', models.TextField(default='暂未填写', null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.User'),
        ),
    ]
