# Generated by Django 2.0.6 on 2020-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='订单id')),
                ('number', models.IntegerField(default=1, verbose_name='购买数量')),
                ('status', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '已取消')], default=1, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(max_length=20, verbose_name='使用者名称')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('status', models.IntegerField(choices=[(1, '管理员'), (2, '用户')], default=2, verbose_name='类型')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('user_number', models.CharField(max_length=18, null=True, verbose_name='身份证号码')),
                ('address', models.TextField(default='暂未填写', null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
