# Generated by Django 2.0.6 on 2020-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='合作商id')),
                ('partname', models.CharField(max_length=20, verbose_name='合作商名称')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('address', models.TextField(default='暂未填写', null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name': '合作商管理',
                'verbose_name_plural': '合作商管理',
                'db_table': 'partner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('ticket_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='票务信息id')),
                ('infoname', models.CharField(max_length=100, verbose_name='演出名称')),
                ('address', models.TextField(verbose_name='演出地址')),
                ('tictype', models.IntegerField(choices=[(1, '演唱会'), (2, '话剧歌剧'), (3, '音乐会'), (4, '展览休闲'), (4, '舞蹈'), (6, '其他')], verbose_name='类型选择')),
                ('show_time', models.DateTimeField(verbose_name='演出时间')),
                ('price', models.FloatField(verbose_name='单张价格')),
                ('status', models.IntegerField(choices=[(1, '在售中'), (2, '已售罄'), (3, '暂停销售')], default=1, verbose_name='销售状态')),
                ('total', models.IntegerField(verbose_name='总票数')),
                ('surplus', models.IntegerField(verbose_name='剩余票数')),
            ],
            options={
                'verbose_name': '票务信息管理',
                'verbose_name_plural': '票务信息管理',
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
