# Generated by Django 2.0.6 on 2020-02-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('partname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('address', models.TextField(default='暂未填写', null=True)),
            ],
            options={
                'db_table': 'partner',
            },
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('ticket_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('infoname', models.TextField()),
                ('address', models.TextField()),
                ('tictype', models.IntegerField(choices=[(1, '演唱会'), (2, '话剧歌剧'), (3, '音乐会'), (4, '展览休闲'), (4, '舞蹈'), (6, '其他')])),
                ('show_time', models.DateTimeField()),
                ('peice', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, '在售中'), (2, '已售罄'), (3, '暂停销售')], default=1)),
                ('total', models.IntegerField()),
                ('surplus', models.IntegerField()),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
    ]
