# Generated by Django 2.0.6 on 2020-02-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'managed': False, 'verbose_name': '合作商管理', 'verbose_name_plural': '合作商管理'},
        ),
        migrations.AlterModelOptions(
            name='ticketinfo',
            options={'managed': False, 'verbose_name': '票务信息管理', 'verbose_name_plural': '票务信息管理'},
        ),
    ]
